/**
 * The half of the lease module a Client Component — or another module's domain — may import.
 * `index.ts` also re-exports the data layer, which is `server-only`.
 */
export {
  currentMonth,
  currentTermEnd,
  isOpen,
  leaseSchedule,
  leaseSummary,
  leaseTermState,
  periodAnchor,
  periodLabel,
  periodOf,
  periodState,
  periodTitle,
  termEndDate,
  verdictApplies,
  LEASE_TERM_STATE_LABELS,
  PERIOD_STATE_LABELS,
  type Lease,
  type LeaseSummary,
  type LeaseTermState,
  type Period,
  type PeriodState,
  type ScheduledMonth,
} from "./domain/lease";
export {
  allAttachments,
  allowedTransitions,
  attachmentLimit,
  attachmentProblem,
  attachmentsLabel,
  canTransition,
  incidentAnchor,
  incidentState,
  isIncidentOpen,
  transitionRequiresNote,
  INCIDENT_PARTY_LABELS,
  INCIDENT_STATES,
  INCIDENT_STATE_LABELS,
  transitionLabel,
  incidentFolder,
  isImageAttachment,
  isOwnAttachmentPath,
  isVideoAttachment,
  INCIDENT_CONTENT_TYPES,
  INCIDENT_DESCRIPTION_MAX,
  INCIDENT_IMAGE_MAX_BYTES,
  INCIDENT_IMAGE_TYPES,
  INCIDENT_TITLE_MAX,
  INCIDENT_VIDEO_MAX_BYTES,
  INCIDENT_VIDEO_TYPES,
  MAX_INCIDENT_ATTACHMENTS,
  type Incident,
  type IncidentAttachment,
  type IncidentContentType,
  type IncidentParty,
  type IncidentState,
  type IncidentUpdate,
} from "./domain/incident";

/**
 * The acta de entrega's pure half, for the components that render it — and for
 * `features/notification`, which needs `handoverAnchor` to build the link a bell entry opens.
 */
export {
  AREA_CONDITIONS,
  AREA_CONDITION_LABELS,
  HANDOVER_KINDS,
  HANDOVER_KIND_LABELS,
  HANDOVER_STATE_LABELS,
  MAX_AREA_PHOTOS,
  MAX_HANDOVER_AREAS,
  MAX_OBJECTION_PHOTOS,
  OBJECTION_NOTE_MAX,
  OBJECTION_NOTE_MIN,
  SUGGESTED_AREAS,
  availableHandoverActions,
  damagedAreas,
  handoverAnchor,
  handoverFolder,
  handoverPhotoProblem,
  handoverState,
  isHandoverSettled,
  type AreaCondition,
  type Handover,
  type HandoverArea,
  type HandoverKind,
  type HandoverPhoto,
  type HandoverState,
} from "./domain/handover";
