/**
 * The half of the lease module a Client Component — or another module's domain — may import.
 * `index.ts` also re-exports the data layer, which is `server-only`.
 */
export {
  currentMonth,
  currentTermEnd,
  isOpen,
  leaseSchedule,
  leaseSummary,
  leaseTermState,
  periodAnchor,
  periodLabel,
  periodOf,
  periodState,
  periodTitle,
  termEndDate,
  verdictApplies,
  LEASE_TERM_STATE_LABELS,
  PERIOD_STATE_LABELS,
  type Lease,
  type LeaseSummary,
  type LeaseTermState,
  type Period,
  type PeriodState,
  type ScheduledMonth,
} from "./domain/lease";
export {
  allAttachments,
  allowedTransitions,
  attachmentLimit,
  attachmentProblem,
  attachmentsLabel,
  canTransition,
  incidentAnchor,
  incidentState,
  isIncidentOpen,
  transitionRequiresNote,
  INCIDENT_PARTY_LABELS,
  INCIDENT_STATES,
  INCIDENT_STATE_LABELS,
  transitionLabel,
  incidentFolder,
  isImageAttachment,
  isOwnAttachmentPath,
  isVideoAttachment,
  INCIDENT_CONTENT_TYPES,
  INCIDENT_DESCRIPTION_MAX,
  INCIDENT_IMAGE_MAX_BYTES,
  INCIDENT_IMAGE_TYPES,
  INCIDENT_TITLE_MAX,
  INCIDENT_VIDEO_MAX_BYTES,
  INCIDENT_VIDEO_TYPES,
  MAX_INCIDENT_ATTACHMENTS,
  type Incident,
  type IncidentAttachment,
  type IncidentContentType,
  type IncidentParty,
  type IncidentState,
  type IncidentUpdate,
} from "./domain/incident";
